@startuml
hide circle
title MDD du système POS
class Produit {
    - id:int
    - nom:string
    - prix:float
    - category:string
    - quantite:int
}
class DBProxy <<Singleton>>{
    - username:string
    - password:string
    --
    + Init()
    - connect()
    + GetCaissier(nom:string):bool
    + SetupLog()
    + OccuperCaisse(nom:string)
    + LibererCaisse(nom:string)
    + ListProduit():[]Produit
    + ListTransactions(): []Transaction
    + GetTransactionByID(transactionID:int):Transaction
    + SetTransactionToDejaRetourne(transactionID:int)
    + EnregistrerTransaction(t:Transaction)
    + GetProduitParID(id:int):Produit
    + GetProduitsParNomWildcard(nomWildcard:string) :[]Produit
}
class Transaction{
    + id:int
    + date:Date
    + Montant:float
    + type:string
    + produitIDs:string
    + caisse:string
    + Deja_retourne:bool
    --
}
class Logger <<Singleton>>{
    - file:File
    --
    + Init(name:string)
    - setPOSName(name string)
    + Info(info:string)
    + Error(error:string)
    + Transaction(t:Transaction, msg:string)
    + GetFile():File
}

class Caisse {
    + ID:int    
	+ Nom:string 
	+ Occupe:bool 
}

class Caissier <<Singleton>>{
    - nom:string
    - cart:[]Produit
    --
    + Nom() string
    + InitianliserPOS()
    + FermerPOS()
    + AfficherProduits():[]Produit
    + AfficherTransactions():[]Transaction
    + TrouverProduit(nomPartiel:string):Produit
    + FaireUneVente(produitID:int):Transaction
    + FaireUnRetour(produitID:int):Transaction
    + AjouterALaCart(produitID:int):float
    + RetirerDeLaCart(produitID:int):float
    + QuantiteDansLaCart(produitID:int):int
    + ViderLaCart()
}

Caissier "1" -- "0..*" Produit

@enduml
