@startuml
hide footbox
title Diagramme de Séquence TotalDeLACart()

actor       Actor       as a
participant Caissier as c
'database    db    as d
'participant logger as l
a -> c : TotalDeLACart()
a <-- c : return total:float
@enduml
